window.LESSON_DATA = [
  {
    "id": "evergreen.lesson8.1-(1)",
    "key": "1-(1)",
    "section": 1,
    "sectionName": "1 空所補充 A・B",
    "format": "blank",
    "focus": "未来の能力 = will be able to",
    "question": "You will (　　　) (　　　) (　　　) pass the exam if you study hard.",
    "answer": "be able to",
    "completed": "You will be able to pass the exam if you study hard.",
    "translation": "一生懸命勉強すれば，あなたは試験に合格できるだろう。",
    "correct": [
      "未来の「できる」を表したいが、will と can はどちらも助動詞なので *will can のように重ねられない。",
      "未来・完了など助動詞 can だけでは作りにくい形では、be able to を使って will be able to とする。"
    ],
    "wrong": [
      "*will can pass は不可。助動詞を2つ続けず、will + be able to + 動詞原形にする。",
      "*will able to pass は be が欠けている。able は形容詞なので be able to のまとまりが必要。"
    ],
    "method": "① will に注目。② 「できる」の can をそのまま置けるか考える。③ 助動詞を重ねられないので be able to に切り替える。",
    "audioQ": "You will blank blank blank pass the exam if you study hard.",
    "audioA": "You will be able to pass the exam if you study hard.",
    "mapPath": ["助動詞","能力・可能","can / be able to","未来の能力"],
    "visual": {"kind":"formula","title":"未来の「できる」","tokens":[{"text":"will","role":"modal"},{"text":"be able to","role":"tail"},{"text":"pass","role":"verb"}],"note":"× will can"},
    "hints": [
      {"en":"Which word fixes the time?","jp":"時を決めている語はどれ？","lookAt":["will"]},
      {"en":"Can two modal verbs stand together?","jp":"助動詞を2つ、そのまま続けられたかな？","lookAt":["will","できるだろう"]},
      {"en":"Use the form of “can” that can follow “will”.","jp":"will の後ろに置ける「できる」の形を思い出そう。","lookAt":["will","pass"]}
    ],
    "outputCue": "一生懸命勉強すれば，あなたは試験に合格できるだろう。",
    "outputChunks": ["You will","be able to","pass the exam","if you study hard."]
  },
  {
    "id": "evergreen.lesson8.1-(2)",
    "key": "1-(2)",
    "section": 1,
    "sectionName": "1 空所補充 A・B",
    "format": "blank",
    "focus": "過去の能力・実現可能性 = was able to",
    "question": "(　　　) Emi (　　　) (　　　) dance to that music?",
    "answer": "Was, able to",
    "completed": "Was Emi able to dance to that music?",
    "translation": "エミはその音楽に合わせて踊ることができたのですか。",
    "correct": [
      "模範解答は Was Emi able to ...?。be able to を過去形にし、疑問文なので Was を主語 Emi の前に出す。",
      "could も過去の能力を表せるが、この設問では3つの空所と be able to の形を使わせる構成になっている。"
    ],
    "wrong": [
      "*Did Emi able to ...? は不可。able は動詞ではなく形容詞なので be動詞が必要。",
      "*Was Emi can ...? のように be動詞と can を重ねない。"
    ],
    "method": "① 空所が主語 Emi の前と後ろにある。② be able to の過去形を作る。③ be動詞の疑問文の語順にする。",
    "audioQ": "blank Emi blank blank dance to that music?",
    "audioA": "Was Emi able to dance to that music?",
    "mapPath": ["助動詞","能力・可能","could / be able to","過去"],
    "visual": {"kind":"compare","title":"過去の「できた」","columns":[{"title":"could","body":"過去に能力があった"},{"title":"was/were able to","body":"過去の能力・実際に可能だったことを表せる","tone":"hot"}]},
    "hints": [
      {"en":"Look at the three blanks around “Emi”.","jp":"Emi の前後にある3つの空所を見よう。","lookAt":["Emi"]},
      {"en":"Which expression can change tense with “be”?","jp":"be動詞を変えて時制を作れる「できる」の表現は？","lookAt":["dance to that music"]},
      {"en":"Make a past-tense question with “be able to”.","jp":"be able to を過去の疑問文にしよう。","lookAt":["Emi","dance"]}
    ],
    "outputCue": "エミはその音楽に合わせて踊ることができたのですか。",
    "outputChunks": ["Was Emi","able to dance","to that music?"]
  },
  {
    "id": "evergreen.lesson8.1-(3)",
    "key": "1-(3)",
    "section": 1,
    "sectionName": "1 空所補充 A・B",
    "format": "blank",
    "focus": "過去の義務・必要 = had to",
    "question": "We (　　　) (　　　) wait for our parents in the rain for three hours.",
    "answer": "had to",
    "completed": "We had to wait for our parents in the rain for three hours.",
    "translation": "私たちは3時間，雨の中で両親を待たなければならなかった。",
    "correct": ["「〜しなければならなかった」は過去の義務・必要。have to を過去形にして had to + 動詞原形。","義務の must は通常、過去の出来事を表す形として *musted を作らないので had to を用いる。"],
    "wrong": ["*musted to wait という形はない。","*had wait は to が欠ける。have to のまとまりを過去にして had to とする。"],
    "method": "日本語の「〜なければならなかった」で過去を確認 → must の過去を無理に作らず had to。",
    "audioQ": "We blank blank wait for our parents in the rain for three hours.",
    "audioA": "We had to wait for our parents in the rain for three hours.",
    "mapPath": ["助動詞","義務・必要","must / have to","過去の必要"],
    "visual": {"kind":"timeline","title":"義務・必要の時制","items":[{"label":"NOW","sub":"must / have to"},{"label":"PAST","sub":"had to","tone":"hot"}]},
    "hints": [
      {"en":"Is the necessity present or past?","jp":"必要だったのは現在？ 過去？","lookAt":["なければならなかった"]},
      {"en":"Does “must” have an ordinary past form?","jp":"must に普通の過去形はあったかな？","lookAt":["wait for our parents"]},
      {"en":"Move “have to” into the past.","jp":"have to を過去形にしてみよう。","lookAt":["We","wait"]}
    ],
    "outputCue": "私たちは3時間，雨の中で両親を待たなければならなかった。",
    "outputChunks": ["We had to","wait for our parents","in the rain","for three hours."]
  },
  {
    "id": "evergreen.lesson8.1-(4)",
    "key": "1-(4)",
    "section": 1,
    "sectionName": "1 空所補充 A・B",
    "format": "blank",
    "focus": "should / must = 義務・必要の強さ",
    "question": "The students (　　　) stay here now because a powerful typhoon is coming.",
    "answer": "should[must]",
    "completed": "The students should stay here now because a powerful typhoon is coming.",
    "translation": "強い台風が近づいているから，生徒たちは今はここにいるべきだ。",
    "correct": ["模範解答は should または must。should は「〜すべきだ」という助言・望ましさ、must は強い必要・義務を表す。","powerful typhoon という安全上の事情があるため、強い必要として must を選ぶ文脈も成立する。"],
    "wrong": ["must と should を完全な同義語として覚えない。must の方が通常、義務・必要の圧力が強い。","had better なら「そうしないとまずい」という警告を強く含むため、この模範解答の中心ではない。"],
    "method": "① 日本語「〜べきだ」を見る。② 助言なら should。③ 安全上の強い必要として言うなら must も可。",
    "audioQ": "The students blank stay here now because a powerful typhoon is coming.",
    "audioA": "The students should stay here now because a powerful typhoon is coming.",
    "mapPath": ["助動詞","義務・必要","should / must","強さ"],
    "visual": {"kind":"scale","title":"必要・助言の強さは文脈で変わる","items":[{"label":"should","sub":"〜すべきだ・したほうがよい"},{"label":"must","sub":"強い必要・義務","tone":"hot"}]},
    "hints": [
      {"en":"What does the Japanese “〜べきだ” suggest first?","jp":"日本語の「〜べきだ」から、まず何を思い出す？","lookAt":["いるべきだ"]},
      {"en":"How serious is the situation?","jp":"状況の切迫度はどのくらい？","lookAt":["powerful typhoon"]},
      {"en":"The model answer accepts two levels of force.","jp":"模範解答では、強さの違う2つの表現が認められている。","lookAt":["stay here now"]}
    ],
    "outputCue": "強い台風が近づいているから，生徒たちは今はここにいるべきだ。",
    "outputChunks": ["The students should","stay here now","because a powerful typhoon","is coming."]
  },
  {
    "id": "evergreen.lesson8.1-(5)",
    "key": "1-(5)",
    "section": 1,
    "sectionName": "1 空所補充 A・B",
    "format": "blank",
    "focus": "mustn’t = 禁止",
    "question": "In any case, you (　　　) speak ill of others behind their back.",
    "answer": "mustn’t",
    "completed": "In any case, you mustn’t speak ill of others behind their back.",
    "translation": "どんな場合でも，他人の陰口を言ってはいけない。",
    "correct": ["mustn’t + 動詞原形で「〜してはいけない」という禁止。","否定の must は「必要がない」ではなく、「してはならない」と行為そのものを禁止する。"],
    "wrong": ["don’t have to は「する必要がない」で、しても構わない余地がある。禁止とは逆。","*mustn’t to speak のように to を置かない。助動詞の後ろは動詞原形。"],
    "method": "「してはいけない」→ 禁止。mustn’t と don’t have to を必ず分ける。",
    "audioQ": "In any case, you blank speak ill of others behind their back.",
    "audioA": "In any case, you mustn’t speak ill of others behind their back.",
    "mapPath": ["助動詞","義務・必要","mustn’t","禁止"],
    "visual": {"kind":"compare","title":"禁止と不必要は正反対","columns":[{"title":"mustn’t","body":"してはいけない = 禁止","tone":"hot"},{"title":"don’t have to","body":"しなくてもよい = 不必要"}]},
    "hints": [
      {"en":"Is the action optional, or forbidden?","jp":"その行為は「しなくてもよい」？ それとも「してはいけない」？","lookAt":["いけない"]},
      {"en":"Do not confuse prohibition with “not necessary.”","jp":"禁止と「必要がない」を混同しないようにしよう。","lookAt":["In any case"]}
    ],
    "outputCue": "どんな場合でも，他人の陰口を言ってはいけない。",
    "outputChunks": ["In any case,","you mustn’t","speak ill of others","behind their back."]
  },
  {
    "id": "evergreen.lesson8.2-(1)",
    "key": "2-(1)",
    "section": 2,
    "sectionName": "2 選択 A・B",
    "format": "choice",
    "focus": "Can you ...? = 依頼",
    "question": "“[ Can I / Can you ] take me to the zoo sometime?” “OK. Let’s go tomorrow.”",
    "choices": ["Can I","Can you"],
    "answer": "Can you",
    "completed": "“Can you take me to the zoo sometime?” “OK. Let’s go tomorrow.”",
    "translation": "「いつか私を動物園に連れていってくれない？」「いいよ。明日，行こう」",
    "correct": ["take me ... の行為をするのは相手 you。相手に行動を頼むので Can you ...?。","Can I ...? は自分 I が行動する許可を求める形で、この文脈とは主語の役割が違う。"],
    "wrong": ["Can I take me ...? だと I と me が同じ人になり、文脈上不自然。","依頼では「誰が実際に行動するか」を先に決めると I / you を取り違えにくい。"],
    "method": "take me to the zoo を誰にしてほしいか → you → Can you ...?",
    "audioQ": "blank take me to the zoo sometime? OK. Let’s go tomorrow.",
    "audioA": "Can you take me to the zoo sometime? OK. Let’s go tomorrow.",
    "mapPath": ["助動詞","能力・許可","can","依頼"],
    "visual": {"kind":"compare","title":"主語で意味が変わる","columns":[{"title":"Can I ...?","body":"私が〜してもよい？ = 許可"},{"title":"Can you ...?","body":"あなたが〜してくれる？ = 依頼","tone":"hot"}]},
    "hints": [
      {"en":"Who will take “me” to the zoo?","jp":"「私」を動物園に連れていくのはだれ？","lookAt":["take me","OK"]},
      {"en":"Is this asking permission, or asking someone to act?","jp":"自分の許可を求める？ それとも相手に行動を頼む？","lookAt":["me","you"]}
    ],
    "outputCue": "いつか私を動物園に連れていってくれない？",
    "outputChunks": ["Can you","take me","to the zoo","sometime?"]
  },
  {
    "id": "evergreen.lesson8.2-(2)",
    "key": "2-(2)",
    "section": 2,
    "sectionName": "2 選択 A・B",
    "format": "choice",
    "focus": "don’t have to = 不必要",
    "question": "Jim will help me with my work tomorrow, so you [ must not / don’t have to ] come.",
    "choices": ["must not","don’t have to"],
    "answer": "don’t have to",
    "completed": "Jim will help me with my work tomorrow, so you don’t have to come.",
    "translation": "ジムが明日，私の仕事を手伝ってくれるでしょうから，あなたは来なくてもいいです。",
    "correct": ["Jim が手伝うので、you が来る「必要がない」。don’t have to が適切。","must not は「来てはいけない」という禁止になり、文意が変わる。"],
    "wrong": ["「〜なくてもよい」を見て must not を選ばない。must not = 禁止。","don’t have to come は来ることを禁止しているのではなく、来る義務をなくしている。"],
    "method": "so の前の理由を見る → 代わりに Jim が来る → 必要なし → don’t have to。",
    "audioQ": "Jim will help me with my work tomorrow, so you blank come.",
    "audioA": "Jim will help me with my work tomorrow, so you don’t have to come.",
    "mapPath": ["助動詞","義務・必要","don’t have to","不必要"],
    "visual": {"kind":"compare","title":"禁止 vs 必要なし","columns":[{"title":"must not","body":"来てはいけない"},{"title":"don’t have to","body":"来る必要はない","tone":"hot"}]},
    "hints": [
      {"en":"Why might “you” not come?","jp":"なぜ you は来なくてもよいの？","lookAt":["Jim will help me","so"]},
      {"en":"Is coming forbidden, or simply unnecessary?","jp":"来ることは禁止？ それとも必要がないだけ？","lookAt":["come"]}
    ],
    "outputCue": "あなたは来なくてもいいです。",
    "outputChunks": ["You don’t have to","come."]
  },
  {
    "id": "evergreen.lesson8.2-(3)",
    "key": "2-(3)",
    "section": 2,
    "sectionName": "2 選択 A・B",
    "format": "choice",
    "focus": "May I ...? = 改まった許可",
    "question": "“[ May I / Can you ] use this dictionary?” “Sure. Go ahead.”",
    "choices": ["May I","Can you"],
    "answer": "May I",
    "completed": "“May I use this dictionary?” “Sure. Go ahead.”",
    "translation": "「この辞書を使ってもよろしいですか」「もちろん。どうぞ」",
    "correct": ["自分 I が辞書を使う許可を求めているので May I ...?。","May I ...? は Can I ...? より改まった許可表現として使われる。"],
    "wrong": ["Can you use this dictionary? では相手 you の能力・行動についてたずねる形になる。","Go ahead. は許可を与える返答なので、前の文も許可を求める形と判断できる。"],
    "method": "返答 Sure. Go ahead. から「許可」の場面と判断 → 主語 I → May I ...?",
    "audioQ": "blank use this dictionary? Sure. Go ahead.",
    "audioA": "May I use this dictionary? Sure. Go ahead.",
    "mapPath": ["助動詞","能力・許可","may","許可を求める"],
    "visual": {"kind":"scale","title":"許可を求める距離感","items":[{"label":"Can I ...?","sub":"一般的"},{"label":"Could I ...?","sub":"丁寧"},{"label":"May I ...?","sub":"改まった丁寧さ","tone":"hot"}]},
    "hints": [
      {"en":"Look at the reply: “Sure. Go ahead.”","jp":"返答の「もちろん。どうぞ」に注目しよう。","lookAt":["Sure","Go ahead"]},
      {"en":"Who wants to use the dictionary?","jp":"辞書を使いたいのはだれ？","lookAt":["I","you"]}
    ],
    "outputCue": "この辞書を使ってもよろしいですか。",
    "outputChunks": ["May I","use this dictionary?"]
  },
  {
    "id": "evergreen.lesson8.2-(4)",
    "key": "2-(4)",
    "section": 2,
    "sectionName": "2 選択 A・B",
    "format": "choice",
    "focus": "can’t = 不許可",
    "question": "Keep off the grass. I mean, you [ can’t / don’t have to ] walk on the grass.",
    "choices": ["can’t","don’t have to"],
    "answer": "can’t",
    "completed": "Keep off the grass. I mean, you can’t walk on the grass.",
    "translation": "芝生に立ち入り禁止。つまり，芝生の上を歩いてはいけません。",
    "correct": ["Keep off the grass. は明確な禁止。can’t はここで「〜してはいけない」という不許可。","don’t have to は「する必要がない」なので、歩いてもよい意味を残してしまう。"],
    "wrong": ["can’t は能力否定だけでなく、不許可にも使える。","前文が禁止標識・規則なら、「できない」より「してはいけない」と読む。"],
    "method": "前の Keep off the grass. の意味を先に取る → 禁止 → can’t。",
    "audioQ": "Keep off the grass. I mean, you blank walk on the grass.",
    "audioA": "Keep off the grass. I mean, you can’t walk on the grass.",
    "mapPath": ["助動詞","能力・許可","can’t","不許可"],
    "visual": {"kind":"flow","title":"標識から意味を決める","nodes":["Keep off","→","禁止","→","can’t walk"]},
    "hints": [
      {"en":"What does “Keep off the grass” mean?","jp":"Keep off the grass はどんな指示？","lookAt":["Keep off the grass"]},
      {"en":"Is this “not necessary” or “not allowed”?","jp":"「必要がない」？ それとも「許可されていない」？","lookAt":["walk on the grass"]}
    ],
    "outputCue": "芝生の上を歩いてはいけません。",
    "outputChunks": ["You can’t","walk","on the grass."]
  },
  {
    "id": "evergreen.lesson8.3-(1)",
    "key": "3-(1)",
    "section": 3,
    "sectionName": "3 日本語訳 C",
    "format": "translate",
    "focus": "can = 一般的・潜在的な可能性",
    "question": "Even a clever person can make mistakes if he/she isn’t careful enough.",
    "questionParts": [{"text":"Even a clever person "},{"text":"can","underline":true},{"text":" make mistakes if he/she isn’t careful enough."}],
    "answer": "十分注意しなければ，賢い人でさえ間違いを起こしうる。",
    "completed": "Even a clever person can make mistakes if he/she isn’t careful enough.",
    "translation": "十分注意しなければ，賢い人でさえ間違いを起こしうる。",
    "correct": ["ここで can は能力ではなく「一般的にそういうことはありうる」という可能性。","Even a clever person と一般化された主語なので、個別の一回の推量ではなく、人間の性質としての可能性を述べている。"],
    "wrong": ["「賢い人は間違えることができる」と能力で訳すと不自然。","can = いつでも『〜できる』ではない。文の主語・文脈から用法を判定する。"],
    "method": "主語が一般化された人・物かを見る → 「そういうことも起こりうる」という can の可能性。",
    "audioQ": "Even a clever person can make mistakes if he or she isn’t careful enough.",
    "audioA": "Even a clever person can make mistakes if he or she isn’t careful enough.",
    "mapPath": ["助動詞","可能性・推量","can","一般的可能性"],
    "visual": {"kind":"flow","title":"can の「潜在的可能性」","nodes":["clever person","→","still possible","→","make mistakes"]},
    "hints": [
      {"en":"Does “can” describe skill here?","jp":"ここで can は「能力」を言っているかな？","lookAt":["clever person","make mistakes"]},
      {"en":"Is this about one event, or something that can happen in general?","jp":"一度の出来事？ それとも一般に起こりうること？","lookAt":["Even","if"]}
    ],
    "outputCue": "十分注意しなければ，賢い人でさえ間違いを起こしうる。",
    "outputChunks": ["Even a clever person","can make mistakes","if he/she isn’t","careful enough."]
  },
  {
    "id": "evergreen.lesson8.3-(2)",
    "key": "3-(2)",
    "section": 3,
    "sectionName": "3 日本語訳 C",
    "format": "translate",
    "focus": "can’t = 強い否定推量",
    "question": "The rumor can’t be true because there is no proof at all.",
    "questionParts": [{"text":"The rumor "},{"text":"can’t","underline":true},{"text":" be true because there is no proof at all."}],
    "answer": "証拠がまったく何もないので，そのうわさは本当であるはずがない。",
    "completed": "The rumor can’t be true because there is no proof at all.",
    "translation": "証拠がまったく何もないので，そのうわさは本当であるはずがない。",
    "correct": ["can’t be + 名詞/形容詞は、根拠から「〜であるはずがない」と可能性を強く否定する推量になる。","because there is no proof at all が「本当ではありえない」と判断する根拠。"],
    "wrong": ["「本当であることができない」という能力訳は不可。","否定推量の can’t と不許可の can’t は、後ろの内容と文脈で分ける。"],
    "method": "because 以下の根拠を確認 → 可能性の否定 → 「〜のはずがない」。",
    "audioQ": "The rumor can’t be true because there is no proof at all.",
    "audioA": "The rumor can’t be true because there is no proof at all.",
    "mapPath": ["助動詞","可能性・推量","can’t","強い否定"],
    "visual": {"kind":"flow","title":"根拠から可能性を閉じる","nodes":["no proof","→","not possible","→","can’t be true"]},
    "hints": [
      {"en":"What evidence does the speaker have?","jp":"話し手にはどんな根拠がある？","lookAt":["no proof at all"]},
      {"en":"Is “be true” an ability?","jp":"be true は「能力」を表している？","lookAt":["can’t be true"]}
    ],
    "outputCue": "そのうわさは本当であるはずがない。",
    "outputText": "The rumor can’t be true.",
    "outputChunks": ["The rumor","can’t be true."]
  },
  {
    "id": "evergreen.lesson8.3-(3)",
    "key": "3-(3)",
    "section": 3,
    "sectionName": "3 日本語訳 C",
    "format": "translate",
    "focus": "must = 強い肯定推量",
    "question": "The bus must be late because of this heavy snow.",
    "questionParts": [{"text":"The bus "},{"text":"must","underline":true},{"text":" be late because of this heavy snow."}],
    "answer": "この大雪のせいでバスは遅れるに違いない。",
    "completed": "The bus must be late because of this heavy snow.",
    "translation": "この大雪のせいでバスは遅れるに違いない。",
    "correct": ["must be はここで義務ではなく、heavy snow という根拠から導く強い推量「〜に違いない」。","主語 the bus に「義務」を課す文脈ではなく、バスの状況を推測している。"],
    "wrong": ["「バスは遅れなければならない」と義務に訳さない。","must の用法は『強い圧力』という共通イメージから、義務にも強い結論にも広がる。"],
    "method": "because of this heavy snow を根拠として読む → 話し手の強い結論 → must = 〜に違いない。",
    "audioQ": "The bus must be late because of this heavy snow.",
    "audioA": "The bus must be late because of this heavy snow.",
    "mapPath": ["助動詞","可能性・推量","must","強い推量"],
    "visual": {"kind":"flow","title":"根拠 → 強い結論","nodes":["heavy snow","→","strong inference","→","must be late"]},
    "hints": [
      {"en":"What causes the speaker’s judgment?","jp":"話し手の判断の根拠は何？","lookAt":["heavy snow"]},
      {"en":"Is the bus being ordered to be late?","jp":"バスに「遅れなさい」と命令しているわけではないね。","lookAt":["must be late"]}
    ],
    "outputCue": "この大雪のせいでバスは遅れるに違いない。",
    "outputChunks": ["The bus","must be late","because of","this heavy snow."]
  },
  {
    "id": "evergreen.lesson8.3-(4)",
    "key": "3-(4)",
    "section": 3,
    "sectionName": "3 日本語訳 C",
    "format": "translate",
    "focus": "would = 控えめな推測",
    "question": "I’m not sure, but my grandmother would be in bed by now.",
    "questionParts": [{"text":"I’m not sure, but my grandmother "},{"text":"would","underline":true},{"text":" be in bed by now."}],
    "answer": "確信はないが，祖母はたぶん今ごろは床についているだろう。",
    "completed": "I’m not sure, but my grandmother would be in bed by now.",
    "translation": "確信はないが，祖母はたぶん今ごろは床についているだろう。",
    "correct": ["I’m not sure が、断定を避けた推測であることを示す。","would はここでは過去の習慣ではなく、will より距離をとった控えめな判断・推測。by now も現在時点の見込みを支える。"],
    "wrong": ["would を見たら必ず「〜したものだった」と訳すのは不可。","時を示す語と文脈を先に見て、過去の習慣・仮定・控えめな推測などを分ける。"],
    "method": "I’m not sure / by now を確認 → 過去の話ではなく今ごろの推測 → would。",
    "audioQ": "I’m not sure, but my grandmother would be in bed by now.",
    "audioA": "I’m not sure, but my grandmother would be in bed by now.",
    "mapPath": ["助動詞","可能性・推量","will / would","控えめな推測"],
    "visual": {"kind":"compare","title":"見通しの距離感","columns":[{"title":"will","body":"比較的直接的な見通し"},{"title":"would","body":"一歩距離を置いた判断・推測","tone":"hot"}]},
    "hints": [
      {"en":"Which words show the speaker’s confidence?","jp":"話し手の確信度が分かる語を探そう。","lookAt":["I’m not sure"]},
      {"en":"What time does “by now” point to?","jp":"by now はいつを指している？","lookAt":["by now"]}
    ],
    "outputCue": "確信はないが，祖母はたぶん今ごろは床についているだろう。",
    "outputChunks": ["I’m not sure,","but my grandmother","would be in bed","by now."]
  },
  {
    "id": "evergreen.lesson8.3-(5)",
    "key": "3-(5)",
    "section": 3,
    "sectionName": "3 日本語訳 C",
    "format": "translate",
    "focus": "may = 可能性の推量",
    "question": "My mother may know about the new shopping mall in the suburb.",
    "questionParts": [{"text":"My mother "},{"text":"may","underline":true},{"text":" know about the new shopping mall in the suburb."}],
    "answer": "母は郊外にあるその新しいショッピングモールについて知っているかもしれない。",
    "completed": "My mother may know about the new shopping mall in the suburb.",
    "translation": "母は郊外にあるその新しいショッピングモールについて知っているかもしれない。",
    "correct": ["may + 動詞原形は、事実だと断定せず「〜かもしれない」と可能性を開いておく推量。","ここは平叙文で母が知っている可能性を述べており、許可の may ではない。"],
    "wrong": ["may を「〜してもよい」と許可だけで訳さない。","may / might の確信度を固定パーセントで暗記せず、文脈上どれだけ控えめに述べているかを見る。"],
    "method": "平叙文 + know について事実かどうかを述べている → may = 「〜かもしれない」。",
    "audioQ": "My mother may know about the new shopping mall in the suburb.",
    "audioA": "My mother may know about the new shopping mall in the suburb.",
    "mapPath": ["助動詞","可能性・推量","may / might","可能性"],
    "visual": {"kind":"flow","title":"可能性を開いておく","nodes":["maybe yes","↔","may","↔","maybe no"]},
    "hints": [
      {"en":"Is anyone giving permission here?","jp":"ここで誰かに許可を与えている？","lookAt":["My mother","know"]},
      {"en":"Is the speaker certain that the mother knows?","jp":"母が知っていると話し手は断定している？","lookAt":["may know"]}
    ],
    "outputCue": "母はその新しいショッピングモールについて知っているかもしれない。",
    "outputChunks": ["My mother","may know about","the new shopping mall","in the suburb."]
  },
  {
    "id": "evergreen.lesson8.4-(1)",
    "key": "4-(1)",
    "section": 4,
    "sectionName": "4 語句整序 総合",
    "format": "order",
    "focus": "Can I ...? = 許可を求める",
    "question": "[ tell / I / about / can / your plan / him ]?",
    "choices": ["tell","I","about","can","your plan","him"],
    "answer": "Can I tell him about your plan",
    "completed": "Can I tell him about your plan?",
    "translation": "彼にあなたの計画について話してもいいですか。",
    "correct": ["疑問文の基本は Can + 主語 + 動詞原形。","tell him about your plan で「彼にあなたの計画について話す」。"],
    "wrong": ["*Do I can ...? としない。can 自身を主語の前に出す。"],
    "method": "まず疑問文の骨格 Can I tell ...? を作り、tell + 人 + about + 内容を続ける。",
    "audioQ": null,
    "audioA": "Can I tell him about your plan?",
    "mapPath": ["助動詞","能力・許可","can","許可"],
    "visual": {"kind":"formula","title":"疑問文の骨格","tokens":[{"text":"Can","role":"modal"},{"text":"I","role":"subject"},{"text":"tell","role":"verb"},{"text":"him","role":"object"},{"text":"about your plan","role":"tail"}]},
    "hints": [
      {"en":"What kind of sentence is this?","jp":"文末の ? から、まず何文を作る？","lookAt":["?"]},
      {"en":"Where does a modal verb go in a question?","jp":"助動詞は疑問文で主語の前？ 後ろ？","lookAt":["can","I"]}
    ],
    "outputCue": "彼にあなたの計画について話してもいいですか。",
    "outputChunks": ["Can I","tell him","about your plan?"]
  },
  {
    "id": "evergreen.lesson8.4-(2)",
    "key": "4-(2)",
    "section": 4,
    "sectionName": "4 語句整序 総合",
    "format": "order",
    "focus": "ought to = 義務・助言",
    "question": "[ rest / to / you / a / ought / take ] anytime when you feel tired.",
    "choices": ["rest","to","you","a","ought","take"],
    "answer": "You ought to take a rest",
    "completed": "You ought to take a rest anytime when you feel tired.",
    "translation": "疲れたときはいつでも休憩を取るべきだ。",
    "correct": ["ought は to とセットで ought to + 動詞原形。","take a rest をひとかたまりとして組み立てる。"],
    "wrong": ["*ought take は不可。should は to を取らないが ought は ought to。"],
    "method": "主語 You → ought to → take a rest の順に骨格を作る。",
    "audioQ": null,
    "audioA": "You ought to take a rest anytime when you feel tired.",
    "mapPath": ["助動詞","義務・必要","should / ought to","助言"],
    "visual": {"kind":"formula","title":"ought の形","tokens":[{"text":"You","role":"subject"},{"text":"ought to","role":"modal"},{"text":"take","role":"verb"},{"text":"a rest","role":"object"}]},
    "hints": [
      {"en":"Which word must stay with “ought”?","jp":"ought とセットで必要な語は？","lookAt":["ought","to"]},
      {"en":"Find the natural phrase meaning “休憩を取る”.","jp":"「休憩を取る」のまとまりを作ろう。","lookAt":["take","a","rest"]}
    ],
    "outputCue": "疲れたときはいつでも休憩を取るべきだ。",
    "outputChunks": ["You ought to","take a rest","anytime","when you feel tired."]
  },
  {
    "id": "evergreen.lesson8.4-(3)",
    "key": "4-(3)",
    "section": 4,
    "sectionName": "4 語句整序 総合",
    "format": "order",
    "focus": "must be = 強い推量",
    "question": "[ a / tennis player / be / the man / professional / must ].",
    "choices": ["a","tennis player","be","the man","professional","must"],
    "answer": "The man must be a professional tennis player",
    "completed": "The man must be a professional tennis player.",
    "translation": "その男性はプロのテニス選手に違いない。",
    "correct": ["S + must + be + 補語で「Sは〜に違いない」という強い推量。","a professional tennis player は名詞句としてまとめる。"],
    "wrong": ["must を義務としか考えないと、この文の意味が取れない。"],
    "method": "主語 The man → must be → a professional tennis player。",
    "audioQ": null,
    "audioA": "The man must be a professional tennis player.",
    "mapPath": ["助動詞","可能性・推量","must","強い推量"],
    "visual": {"kind":"formula","title":"推量の must","tokens":[{"text":"The man","role":"subject"},{"text":"must","role":"modal"},{"text":"be","role":"verb"},{"text":"a professional tennis player","role":"tail"}]},
    "hints": [
      {"en":"Is “must” giving the man an order?","jp":"must は男性に命令している？","lookAt":["the man","professional tennis player"]},
      {"en":"What pattern follows an inference with “must”?","jp":"「〜に違いない」を be と組み合わせる形を思い出そう。","lookAt":["must","be"]}
    ],
    "outputCue": "その男性はプロのテニス選手に違いない。",
    "outputChunks": ["The man","must be","a professional","tennis player."]
  },
  {
    "id": "evergreen.lesson8.4-(4)",
    "key": "4-(4)",
    "section": 4,
    "sectionName": "4 語句整序 総合",
    "format": "order",
    "focus": "Can S be ...? = 強い疑問",
    "question": "[ Jack’s / be / can / cousin / that girl ]? I don’t think she is.",
    "choices": ["Jack’s","be","can","cousin","that girl"],
    "answer": "Can that girl be Jack’s cousin",
    "completed": "Can that girl be Jack’s cousin? I don’t think she is.",
    "translation": "あの女の子がジャックのいとこなの？ 違うと思うな。",
    "correct": ["Can + S + be ...? で「Sが〜でありうるのか」という強い疑いを表せる。","I don’t think she is. が疑いの文脈を補強する。"],
    "wrong": ["能力の can ではなく、可能性を問う can。"],
    "method": "疑問文なので Can を先頭 → that girl → be → Jack’s cousin。",
    "audioQ": null,
    "audioA": "Can that girl be Jack’s cousin? I don’t think she is.",
    "mapPath": ["助動詞","可能性・推量","can","強い疑問"],
    "visual": {"kind":"flow","title":"強い疑問","nodes":["Can","that girl","be","Jack’s cousin?"]},
    "hints": [
      {"en":"What does the second sentence tell you?","jp":"後ろの I don’t think she is. から、話し手の気持ちは？","lookAt":["I don’t think she is"]},
      {"en":"Build a modal question first.","jp":"まず助動詞の疑問文の語順を作ろう。","lookAt":["can","that girl","be"]}
    ],
    "outputCue": "あの女の子がジャックのいとこなの？",
    "outputChunks": ["Can that girl","be Jack’s cousin?"]
  },
  {
    "id": "evergreen.lesson8.4-(5)",
    "key": "4-(5)",
    "section": 4,
    "sectionName": "4 語句整序 総合",
    "format": "order",
    "focus": "should = 期待・見込み「〜のはずだ」",
    "question": "Fred [ be / a few days / in / back / should ]. He said so.",
    "choices": ["be","a few days","in","back","should"],
    "answer": "Fred should be back in a few days",
    "completed": "Fred should be back in a few days. He said so.",
    "translation": "フレッドは2，3日で戻ってくるはずだ。そう言ってたよ。",
    "correct": ["should は義務だけでなく、予定・情報からの推量「〜のはずだ」。","He said so. が判断の根拠になっている。"],
    "wrong": ["「戻るべきだ」と義務にしない。文脈は本人の発言に基づく見込み。"],
    "method": "He said so. → 予定に基づく期待 → should be back。",
    "audioQ": null,
    "audioA": "Fred should be back in a few days. He said so.",
    "mapPath": ["助動詞","可能性・推量","should / ought to","期待"],
    "visual": {"kind":"flow","title":"情報 → 期待","nodes":["He said so","→","expected","→","should be back"]},
    "hints": [
      {"en":"What evidence do we have?","jp":"何を根拠に判断している？","lookAt":["He said so"]},
      {"en":"Is this advice, or an expectation?","jp":"「戻るべき」という助言？ それとも「戻るはず」という見込み？","lookAt":["should","back"]}
    ],
    "outputCue": "フレッドは2，3日で戻ってくるはずだ。",
    "outputChunks": ["Fred","should be back","in a few days."]
  },
  {
    "id": "evergreen.lesson8.4-(6)",
    "key": "4-(6)",
    "section": 4,
    "sectionName": "4 語句整序 総合",
    "format": "order",
    "focus": "will = 予測",
    "question": "[ will / sister / hungry / be / after / my ] basketball practice.",
    "choices": ["will","sister","hungry","be","after","my"],
    "answer": "My sister will be hungry after",
    "completed": "My sister will be hungry after basketball practice.",
    "translation": "姉［妹］はバスケットボールの練習の後でたぶんお腹がすいているだろう。",
    "correct": ["未来の状況を見通して will be hungry と予測している。","will の後ろは動詞原形なので be。"],
    "wrong": ["*will is hungry は不可。will + be + 形容詞。"],
    "method": "主語 My sister → will → be hungry → after basketball practice。",
    "audioQ": null,
    "audioA": "My sister will be hungry after basketball practice.",
    "mapPath": ["助動詞","可能性・推量","will / would","予測"],
    "visual": {"kind":"timeline","title":"今から先を見通す","items":[{"label":"NOW","sub":"prediction"},{"label":"AFTER PRACTICE","sub":"hungry","tone":"hot"}]},
    "hints": [
      {"en":"Who is the subject?","jp":"主語になるまとまりは？","lookAt":["my","sister"]},
      {"en":"What form follows “will”?","jp":"will の直後の be動詞はどの形？","lookAt":["will","be","hungry"]}
    ],
    "outputCue": "姉［妹］はバスケットボールの練習の後でお腹がすいているだろう。",
    "outputChunks": ["My sister","will be hungry","after","basketball practice."]
  },
  {
    "id": "evergreen.lesson8.4-(7)",
    "key": "4-(7)",
    "section": 4,
    "sectionName": "4 語句整序 総合",
    "format": "order",
    "focus": "had better not = 強い忠告",
    "question": "[ better / you / ask / not / Rachel / had ] for advice.",
    "choices": ["better","you","ask","not","Rachel","had"],
    "answer": "You had better not ask Rachel",
    "completed": "You had better not ask Rachel for advice.",
    "translation": "あなたはレイチェルに助言を求めないほうがよい。",
    "correct": ["had better not + 動詞原形で「〜しないほうがよい」。","had があっても過去時制ではなく、まとまった忠告表現。"],
    "wrong": ["*had not better ask を基本形にしない。not は better の後ろ。","*had better not to ask と to を置かない。"],
    "method": "You → had better not → ask Rachel → for advice。",
    "audioQ": null,
    "audioA": "You had better not ask Rachel for advice.",
    "mapPath": ["助動詞","義務・必要","had better","強い忠告"],
    "visual": {"kind":"formula","title":"否定の位置","tokens":[{"text":"You","role":"subject"},{"text":"had better","role":"modal"},{"text":"not","role":"neg"},{"text":"ask","role":"verb"},{"text":"Rachel","role":"object"}]},
    "hints": [
      {"en":"Keep “had better” together first.","jp":"まず had better をひとかたまりにしよう。","lookAt":["had","better"]},
      {"en":"Where does “not” go?","jp":"否定の not はどこに入る？","lookAt":["better","not","ask"]}
    ],
    "outputCue": "あなたはレイチェルに助言を求めないほうがよい。",
    "outputChunks": ["You had better not","ask Rachel","for advice."]
  },
  {
    "id": "evergreen.lesson8.TRY-(1)",
    "key": "TRY-(1)",
    "section": 5,
    "sectionName": "TRY 英作文",
    "format": "write",
    "focus": "can / be able to = 現在の能力",
    "question": "メアリーは中国語を書くことができる。",
    "answer": "Mary can[is able to] write Chinese.",
    "completed": "Mary can write Chinese.",
    "translation": "メアリーは中国語を書くことができる。",
    "correct": ["模範解答は can または is able to。現在の能力なのでどちらも使える。","can の後ろは動詞原形 write。be able to を使うなら主語 Mary に合わせて is able to。"],
    "wrong": ["*Mary can writes / *Mary can to write は不可。","*Mary able to write は be動詞 is が必要。"],
    "method": "主語 Mary → 現在の能力 → can + write、または is able to + write。",
    "audioQ": null,
    "audioA": "Mary can write Chinese.",
    "mapPath": ["助動詞","能力・可能","can / be able to","能力"],
    "visual": {"kind":"compare","title":"模範解答ではどちらも可","columns":[{"title":"can","body":"Mary can write ...","tone":"hot"},{"title":"be able to","body":"Mary is able to write ..."}]},
    "hints": [
      {"en":"Is this ability, permission, or possibility?","jp":"これは能力・許可・可能性のどれ？","lookAt":["できる"]},
      {"en":"What form follows “can”?","jp":"can の後ろの動詞はどの形？","lookAt":["write"]}
    ],
    "outputCue": "メアリーは中国語を書くことができる。",
    "outputChunks": ["Mary can","write Chinese."]
  },
  {
    "id": "evergreen.lesson8.TRY-(2)",
    "key": "TRY-(2)",
    "section": 5,
    "sectionName": "TRY 英作文",
    "format": "write",
    "focus": "may / might / could = 個別の可能性",
    "question": "トムは夜遅くに外出するかもしれない。",
    "answer": "Tom may[might/could] go out late at night.",
    "completed": "Tom may go out late at night.",
    "translation": "トムは夜遅くに外出するかもしれない。",
    "correct": ["模範解答は may / might / could のいずれも可。個別の状況について「〜かもしれない」と可能性を述べる。","これらの強さを固定のパーセントで機械的に並べるより、文脈上の控えめさ・距離感として理解する方が安全。"],
    "wrong": ["can は一般的・理論的可能性には使えるが、この一回の人物についての肯定推量では may / might / could が自然。","*may to go のように to を置かない。助動詞 + 動詞原形。"],
    "method": "「〜かもしれない」＋個別の状況 → may / might / could + go。",
    "audioQ": null,
    "audioA": "Tom may go out late at night.",
    "mapPath": ["助動詞","可能性・推量","may / might / could","個別の可能性"],
    "visual": {"kind":"compare","title":"「かもしれない」の選択肢","columns":[{"title":"may / might","body":"可能性を提示"},{"title":"could","body":"ありうる可能性を控えめに提示","tone":"hot"}]},
    "hints": [
      {"en":"Is this a general truth, or one possible event?","jp":"一般論？ それとも一回の出来事の可能性？","lookAt":["Tom","late at night"]},
      {"en":"Which modals can mean “〜かもしれない” here?","jp":"この場面で「〜かもしれない」を表せる助動詞を思い出そう。","lookAt":["かもしれない"]}
    ],
    "outputCue": "トムは夜遅くに外出するかもしれない。",
    "outputChunks": ["Tom may","go out","late at night."]
  },
  {
    "id": "evergreen.lesson8.TRY-(3)",
    "key": "TRY-(3)",
    "section": 5,
    "sectionName": "TRY 英作文",
    "format": "write",
    "focus": "must / have to = 義務・必要",
    "question": "あなたは夕食後，皿を洗わなければならない。",
    "answer": "You must[have to] wash[do] the dishes after dinner.",
    "completed": "You must wash the dishes after dinner.",
    "translation": "あなたは夕食後，皿を洗わなければならない。",
    "correct": ["模範解答は must / have to の両方を認め、wash the dishes / do the dishes の両方が可能。","must は強い義務・必要、have to は事情・規則による必要を表しやすいが、実際には重なる場面も多い。"],
    "wrong": ["*must to wash は不可。must + 動詞原形。","have to を使う場合は You have to wash ... と have を落とさない。"],
    "method": "「〜しなければならない」→ must / have to。次に wash the dishes / do the dishes の語句を作る。",
    "audioQ": null,
    "audioA": "You must wash the dishes after dinner.",
    "mapPath": ["助動詞","義務・必要","must / have to","義務"],
    "visual": {"kind":"compare","title":"模範解答ではどちらも可","columns":[{"title":"must","body":"強い義務・必要","tone":"hot"},{"title":"have to","body":"事情・規則による必要"}]},
    "hints": [
      {"en":"What meaning does “〜なければならない” express?","jp":"「〜なければならない」は何の意味？","lookAt":["なければならない"]},
      {"en":"Remember the two accepted forms in this lesson.","jp":"このLessonで認められている2つの義務表現を思い出そう。","lookAt":["皿を洗う"]}
    ],
    "outputCue": "あなたは夕食後，皿を洗わなければならない。",
    "outputChunks": ["You must","wash the dishes","after dinner."]
  }
];
