(()=>{
'use strict';
const refs=window.LESSON_REFERENCES||null;
const app=document.getElementById('app');
const toolbar=document.querySelector('.toolbar');
const stageEl=document.getElementById('stage');
if(!app||!toolbar||!stageEl)return;
const esc=(s='')=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));

const patch=document.createElement('style');
patch.textContent=`
:root{--l8-reading:"Iowan Old Style","Baskerville","Palatino Linotype","Book Antiqua",Georgia,serif;--l8-ui:"Avenir Next",Avenir,"Segoe UI","Helvetica Neue",Arial,sans-serif;--l8-jp:"Hiragino Sans","Yu Gothic UI","Yu Gothic",Meiryo,sans-serif}
.hint-mark{background:#ffe19a;color:#172033;border-radius:4px;padding:0 .08em;box-shadow:inset 0 -3px 0 #e8ad31}.map-btn{font-size:14px!important;min-width:auto!important;width:auto!important;padding:0 12px!important;white-space:nowrap}.toolbar.is-collapsed .map-btn{display:none!important}
.question{font-family:var(--l8-reading)!important;font-weight:700!important;letter-spacing:.005em!important}.completed,.backup-chunk,.quick-answer,.last-try-answer,.final-choice-answer strong{font-family:var(--l8-reading)!important}.hint-en,.output-instruction b,.final-lead,.guide-card b,.teacher-voice-copy .en{font-family:var(--l8-ui)!important}.hint-jp,.output-instruction span,.final-lead-jp,.guide-card p,.teacher-voice-copy .jp,.backup-ready span{font-family:var(--l8-jp)!important}
#stage{padding:30px 42px 90px!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"])>h1{display:none!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"]) .topline{margin-bottom:8px!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"]) .question-card{padding:13px 20px!important;border-radius:18px!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"]) .question{font-size:clamp(20px,1.9vw,28px)!important;line-height:1.24!important;padding-right:60px!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"]) .question-card .audio-btn{right:13px!important;top:50%!important;transform:translateY(-50%)!important;min-width:42px!important;height:42px!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"]) .content{margin-top:11px!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"]) .stage-panel{padding:14px 19px!important;border-radius:18px!important}#stage[data-lesson-stage="problem"] .question{font-size:clamp(23px,2.2vw,32px)!important;line-height:1.3!important}.stage-hint{display:none!important}
#stage[data-lesson-stage^="hint:"] .hint-panel{padding:14px 20px!important}#stage[data-lesson-stage^="hint:"] .hint-en{font-size:clamp(22px,2.2vw,31px)!important;line-height:1.2!important}#stage[data-lesson-stage^="hint:"] .hint-jp{font-size:clamp(13px,1.2vw,17px)!important;margin-top:5px!important}#stage[data-lesson-stage^="hint:"] .hint-look{margin-top:10px!important;gap:7px!important}#stage[data-lesson-stage^="hint:"] .hint-look span{padding:6px 11px!important;font-size:clamp(14px,1.35vw,18px)!important}#stage[data-lesson-stage^="hint:"] .hint-visual{margin-top:9px!important}
#stage[data-lesson-stage="answer"] .answer-main{font-size:clamp(22px,2.2vw,33px)!important;line-height:1.28!important;margin:0 0 6px!important}#stage[data-lesson-stage="answer"] .completed{font-size:clamp(16px,1.55vw,22px)!important;line-height:1.32!important;padding:9px 13px!important;margin-top:7px!important}#stage[data-lesson-stage="answer"] .output-actions,#stage[data-lesson-stage="translation"] .output-actions{margin-top:7px!important}#stage[data-lesson-stage="reason"] .method{margin-top:7px!important;padding:8px 11px!important}#stage[data-lesson-stage="reason"] .bullets li{font-size:clamp(14px,1.35vw,18px)!important;line-height:1.35!important;margin-bottom:5px!important}#stage[data-lesson-stage="wrong"] .wrong-list{gap:6px!important}#stage[data-lesson-stage="wrong"] .wrong-item{padding:8px 11px!important;font-size:clamp(13px,1.25vw,17px)!important;line-height:1.3!important}#stage[data-lesson-stage="translation"] .jp-translation{font-size:clamp(21px,2.15vw,31px)!important;line-height:1.4!important;margin:0!important}
#stage[data-lesson-stage="output"] .question-card{display:none!important}#stage[data-lesson-stage="output"] .content{margin-top:6px!important}#stage[data-lesson-stage="output"] .stage-panel{padding:13px 18px!important}#stage[data-lesson-stage="output"] .panel-label{margin-bottom:6px!important}#stage[data-lesson-stage="output"] .output-instruction{gap:2px!important;margin-bottom:6px!important}#stage[data-lesson-stage="output"] .output-instruction b{font-size:clamp(14px,1.35vw,18px)!important}#stage[data-lesson-stage="output"] .output-instruction span{font-size:12px!important}#stage[data-lesson-stage="output"] .backup-practice{gap:7px!important}#stage[data-lesson-stage="output"] .backup-cue{font-size:clamp(18px,1.8vw,25px)!important;line-height:1.36!important;padding:9px 13px!important;border-radius:13px!important}#stage[data-lesson-stage="output"] .backup-chunks{min-height:48px!important;padding:9px 12px!important;border-radius:13px!important;gap:6px!important}#stage[data-lesson-stage="output"] .backup-chunk{font-size:clamp(16px,1.55vw,21px)!important;line-height:1.25!important}#stage[data-lesson-stage="output"] .output-actions{margin-top:7px!important}#stage[data-lesson-stage="output"] .action-btn{padding:8px 13px!important;font-size:13px!important}
.final-stage{overflow:hidden!important;padding:27px 42px 90px!important}.final-stage .final-screen{height:auto!important;max-height:100%!important;align-content:start!important}.final-stage .final-kicker{margin-bottom:4px!important}.final-stage .final-screen h1{font-size:clamp(28px,3vw,43px)!important;margin-bottom:3px!important}.final-stage .final-lead{font-size:clamp(14px,1.35vw,18px)!important}.final-stage .final-lead-jp{font-size:12px!important;margin:2px 0 9px!important}.final-stage .quick-grid{gap:7px!important}.final-stage .quick-card{min-height:68px!important;padding:9px 11px!important;border-radius:13px!important}.final-stage .quick-cue{font-size:clamp(14px,1.35vw,18px)!important;padding-right:68px!important}.final-stage .quick-answer{margin-top:5px!important;padding:6px 9px!important;font-size:clamp(14px,1.3vw,18px)!important}.final-stage .mini-check{right:9px!important;top:9px!important;padding:5px 8px!important;font-size:12px!important}.final-stage .final-choice-list,.final-stage .last-try-list{gap:6px!important}.final-stage .final-choice-card,.final-stage .last-try-card{min-height:0!important;padding:9px 11px!important;border-radius:13px!important}.final-stage .final-choice-answer,.final-stage .last-try-answer{margin-top:5px!important;padding:6px 9px!important}.final-stage .backup-practice{gap:7px!important}.final-stage .backup-cue{font-size:clamp(18px,1.8vw,25px)!important;padding:9px 13px!important;line-height:1.36!important}.final-stage .backup-chunks{min-height:48px!important;padding:9px 12px!important;gap:6px!important}.final-stage .backup-chunk{font-size:clamp(16px,1.55vw,21px)!important}.final-stage .output-actions{margin-top:7px!important}.final-stage .action-btn{padding:8px 13px!important;font-size:13px!important}
@media (max-height:820px) and (min-width:701px){#stage{padding:24px 38px 82px!important}#stage[data-lesson-stage="problem"]>h1{font-size:clamp(30px,3vw,42px)!important;margin-bottom:10px!important}#stage[data-lesson-stage="problem"] .question-card{padding:17px 23px!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"]) .question-card{padding:11px 18px!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"]) .content{margin-top:8px!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"]) .stage-panel{padding:11px 16px!important}#stage[data-lesson-stage^="hint:"] .hint-en{font-size:clamp(20px,2vw,28px)!important}.final-stage{padding:22px 38px 82px!important}.final-stage .quick-card{min-height:62px!important;padding:7px 10px!important}}
@media(max-width:700px){#stage{padding:18px 16px 88px!important}#stage[data-lesson-stage]:not([data-lesson-stage="problem"]) .question-card{display:block}#stage[data-lesson-stage="output"] .question-card{display:none!important}.final-stage{overflow:auto!important;padding:18px 16px 88px!important}}
`;
document.head.appendChild(patch);

function isWordChar(ch){return !!ch&&/[A-Za-z0-9_]/.test(ch)}
function findHighlightRanges(text,terms=[]){const source=String(text||''),lower=source.toLowerCase(),c=[];for(const raw of [...terms].filter(Boolean).map(String).sort((a,b)=>b.length-a.length)){const needle=raw.toLowerCase();let from=0;while(needle&&from<source.length){const start=lower.indexOf(needle,from);if(start<0)break;const end=start+needle.length,leftOk=!isWordChar(raw[0])||start===0||!isWordChar(source[start-1]),rightOk=!isWordChar(raw[raw.length-1])||end===source.length||!isWordChar(source[end]);if(leftOk&&rightOk)c.push({start,end,length:end-start});from=start+Math.max(1,needle.length)}}c.sort((a,b)=>a.start-b.start||b.length-a.length);const picked=[];for(const x of c){if(!picked.some(p=>x.start<p.end&&x.end>p.start))picked.push(x)}return picked.sort((a,b)=>a.start-b.start)}
function splitHighlight(text,terms=[]){const source=String(text||''),ranges=findHighlightRanges(source,terms);if(!ranges.length)return esc(source);let out='',cursor=0;for(const r of ranges){out+=esc(source.slice(cursor,r.start));out+=`<mark class="hint-mark">${esc(source.slice(r.start,r.end))}</mark>`;cursor=r.end}return out+esc(source.slice(cursor))}
function renderQuestionText(q,state){const hintIndex=String(state?.stage||'').startsWith('hint:')?Number(String(state.stage).split(':')[1]):-1,terms=hintIndex>=0?(q?.hints?.[hintIndex]?.lookAt||[]):[],node=document.querySelector('.question');if(!node)return;const parts=Array.isArray(q?.questionParts)?q.questionParts:[{text:q?.question||''}];node.innerHTML=parts.map(part=>{const inner=splitHighlight(part?.text||'',terms);return part?.underline?`<span class="source-underline">${inner}</span>`:inner}).join('')}
function renderVisual(v){if(!v||!v.kind)return'';const title=v.title?`<div class="viz-title">${esc(v.title)}</div>`:'';if(v.kind==='flow')return `${title}<div class="viz-flow">${(v.nodes||[]).map(x=>`<div class="viz-node ${x==='→'?'arrow':''}">${esc(x)}</div>`).join('')}</div>`;if(v.kind==='compare')return `${title}<div class="viz-compare">${(v.columns||[]).map(x=>`<div class="viz-col ${x.tone==='hot'?'hot':''}"><b>${esc(x.title)}</b><span>${esc(x.body)}</span></div>`).join('')}</div>`;if(v.kind==='timeline')return `${title}<div class="viz-timeline">${(v.items||[]).map(x=>`<div class="viz-time ${x.tone||''}"><b>${esc(x.label)}</b><span>${esc(x.sub||'')}</span></div>`).join('<div class="viz-line">→</div>')}</div>`;if(v.kind==='scale')return `${title}<div class="viz-scale">${(v.items||[]).map((x,i)=>`<div class="viz-scale-item ${x.tone==='hot'?'hot':''}"><span class="viz-rank">${i+1}</span><b>${esc(x.label)}</b><small>${esc(x.sub||'')}</small></div>`).join('')}</div>`;if(v.kind==='formula')return `${title}<div class="viz-formula">${(v.tokens||[]).map(x=>`<span class="viz-token ${esc(x.role||'')}">${esc(x.text)}</span>`).join('<span class="viz-plus">＋</span>')}</div>${v.note?`<div class="viz-note">${esc(v.note)}</div>`:''}`;return''}
function enhanceQuestion(state){const inQuestion=state.slideIndex>=0&&state.slideIndex<(window.LESSON_DATA||[]).length;if(inQuestion)stageEl.dataset.lessonStage=state.stage||'problem';else stageEl.removeAttribute('data-lesson-stage');const q=window.LessonEngine?.getCurrent?.();if(!q)return;renderQuestionText(q,state);document.querySelectorAll('.where-am-i,.question-viz').forEach(n=>n.remove());if(!inQuestion)return;const afterAnswer=['answer','reason','wrong','translation','output'].includes(state.stage);if(afterAnswer&&Array.isArray(q.mapPath)&&q.mapPath.length){const where=document.createElement('div');where.className='where-am-i';where.innerHTML=`<span>Now</span>${q.mapPath.map((x,i)=>`<b>${esc(x)}</b>${i<q.mapPath.length-1?'<i>›</i>':''}`).join('')}`;document.querySelector('.topline')?.insertAdjacentElement('afterend',where)}if(state.stage==='reason'&&q.visual){const panel=document.querySelector('.stage-panel');if(panel){const wrap=document.createElement('div');wrap.className='question-viz';wrap.innerHTML=renderVisual(q.visual);panel.appendChild(wrap)}}}

function renderReferenceSection(section){const lead=section.lead?`<p class="map-lead">${esc(section.lead)}</p>`:'';if(section.type==='map')return `${lead}<div class="concept-grid">${(section.groups||[]).map(g=>`<article class="concept-card ${g.lesson?'in-lesson':'outside'}"><div class="concept-status">${g.lesson?'LESSON 8':'周辺'}</div><h3>${esc(g.title)}</h3><div class="concept-items">${(g.items||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div><p>${esc(g.note||'')}</p></article>`).join('')}</div>`;if(section.type==='branch')return `${lead}<div class="branch-grid">${(section.rows||[]).map(r=>`<article class="branch-card"><h3>${esc(r.head)}</h3><div class="branch-core">${esc(r.core)}</div><div class="branch-list">${(r.branches||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div></article>`).join('')}</div>`;if(section.type==='compare')return `${lead}<div class="map-compare">${(section.columns||[]).map(c=>`<article><span class="map-badge">${esc(c.badge||'')}</span><h3>${esc(c.title)}</h3><p>${esc(c.body)}</p><strong>${esc(c.meaning||'')}</strong></article>`).join('')}</div>`;if(section.type==='matrix')return `${lead}<div class="matrix-wrap"><table><thead><tr>${(section.headers||[]).map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${(section.rows||[]).map(row=>`<tr>${row.map((x,i)=>`<${i===0?'th':'td'}>${esc(x)}</${i===0?'th':'td'}>`).join('')}</tr>`).join('')}</tbody></table></div>${section.note?`<div class="map-note">${esc(section.note)}</div>`:''}`;return lead}
function buildMap(){if(!refs)return;const btn=document.createElement('button');btn.type='button';btn.id='conceptMapBtn';btn.className='icon-btn map-btn';btn.setAttribute('aria-label','Lesson 8 全体地図を開く');btn.title='今どこを学んでいるか全体地図で確認';btn.textContent='🗺 地図';toolbar.insertBefore(btn,document.getElementById('menuBtn')?.nextSibling||toolbar.firstChild);const drawer=document.createElement('div');drawer.id='conceptMapDrawer';drawer.className='concept-map-drawer';drawer.hidden=true;drawer.innerHTML=`<div class="concept-map-card" role="dialog" aria-modal="true" aria-labelledby="conceptMapTitle"><header class="concept-map-head"><div><small>REFERENCE MAP</small><h2 id="conceptMapTitle">${esc(refs.title||'Lesson Map')}</h2><p>${esc(refs.subtitle||'')}</p></div><button type="button" id="conceptMapClose" class="map-close" aria-label="閉じる">×</button></header><nav class="map-tabs">${(refs.sections||[]).map((s,i)=>`<button type="button" data-map-tab="${i}" class="${i===0?'active':''}">${esc(s.title)}</button>`).join('')}</nav><main id="conceptMapBody" class="concept-map-body"></main></div>`;document.body.appendChild(drawer);const body=drawer.querySelector('#conceptMapBody'),tabs=[...drawer.querySelectorAll('[data-map-tab]')];function show(i){const s=refs.sections?.[i];if(!s)return;tabs.forEach((t,n)=>t.classList.toggle('active',n===i));body.innerHTML=`<section><h2>${esc(s.title)}</h2>${renderReferenceSection(s)}</section>`}function open(){drawer.hidden=false;show(0);drawer.querySelector('#conceptMapClose').focus()}function close(){drawer.hidden=true;btn.focus()}btn.addEventListener('click',e=>{e.stopPropagation();open()});drawer.querySelector('#conceptMapClose').addEventListener('click',close);drawer.addEventListener('click',e=>{if(e.target===drawer)close()});tabs.forEach(t=>t.addEventListener('click',()=>show(Number(t.dataset.mapTab))));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!drawer.hidden)close()})}
buildMap();window.addEventListener('lesson:render',e=>enhanceQuestion(e.detail||{}));requestAnimationFrame(()=>enhanceQuestion(window.LessonEngine?.getState?.()||{}));
})();