window.LESSON_DATA = [
  {
    "id": "evergreen.lesson10.1-(1)",
    "key": "1-(1)",
    "section": 1,
    "sectionName": "1 和訳 A",
    "format": "translate",
    "focus": "should have + p.p.：過去の出来事について「〜したはずだ」",
    "question": "Ms. Black should have arrived at the airport by now. Her flight is leaving in a few minutes.",
    "answer": "ブラックさんは今ごろ空港に着いたはずだ。彼女が乗る飛行機は数分で出発する。",
    "completed": "Ms. Black should have arrived at the airport by now. Her flight is leaving in a few minutes.",
    "translation": "ブラックさんは今ごろ空港に着いたはずだ。彼女が乗る飛行機は数分で出発する。",
    "audioQ": "Ms. Black should have arrived at the airport by now. Her flight is leaving in a few minutes.",
    "audioA": "Ms. Black should have arrived at the airport by now. Her flight is leaving in a few minutes."
  },
  {
    "id": "evergreen.lesson10.1-(2)",
    "key": "1-(2)",
    "section": 1,
    "sectionName": "1 和訳 A",
    "format": "translate",
    "focus": "cannot have + p.p.：過去について「〜したはずがない」",
    "question": "Alan cannot have been busy at that time. He and I had finished the experiment by then.",
    "answer": "アランはそのとき忙しかったはずがない。彼と私はそのときまでに実験を終えていた。",
    "completed": "Alan cannot have been busy at that time. He and I had finished the experiment by then.",
    "translation": "アランはそのとき忙しかったはずがない。彼と私はそのときまでに実験を終えていた。",
    "audioQ": "Alan cannot have been busy at that time. He and I had finished the experiment by then.",
    "audioA": "Alan cannot have been busy at that time. He and I had finished the experiment by then."
  },
  {
    "id": "evergreen.lesson10.1-(3)",
    "key": "1-(3)",
    "section": 1,
    "sectionName": "1 和訳 A",
    "format": "translate",
    "focus": "needn’t have + p.p.：する必要はなかったのに（実際はした）",
    "question": "You need not have made a reservation at the hotel for me. I had planned to stay with my aunt.",
    "answer": "あなたは私のためにホテルを予約する必要はなかったのに。私は，おばのところに泊まる予定にしていたんだ。",
    "completed": "You need not have made a reservation at the hotel for me. I had planned to stay with my aunt.",
    "translation": "あなたは私のためにホテルを予約する必要はなかったのに。私は，おばのところに泊まる予定にしていたんだ。",
    "audioQ": "You need not have made a reservation at the hotel for me. I had planned to stay with my aunt.",
    "audioA": "You need not have made a reservation at the hotel for me. I had planned to stay with my aunt."
  },
  {
    "id": "evergreen.lesson10.1-(4)",
    "key": "1-(4)",
    "section": 1,
    "sectionName": "1 和訳 A",
    "format": "translate",
    "focus": "may have + p.p.：過去の可能性「〜したかもしれない」",
    "question": "It’s already 10:30, but Jill and Jake are not here. They may have taken the wrong train.",
    "answer": "もう 10 時 30 分なのに，ジルとジェイクがここにいない。彼らは間違った電車に乗ったのかもしれない。",
    "completed": "It’s already 10:30, but Jill and Jake are not here. They may have taken the wrong train.",
    "translation": "もう 10 時 30 分なのに，ジルとジェイクがここにいない。彼らは間違った電車に乗ったのかもしれない。",
    "audioQ": "It’s already 10:30, but Jill and Jake are not here. They may have taken the wrong train.",
    "audioA": "It’s already 10:30, but Jill and Jake are not here. They may have taken the wrong train."
  },
  {
    "id": "evergreen.lesson10.1-(5)",
    "key": "1-(5)",
    "section": 1,
    "sectionName": "1 和訳 A",
    "format": "translate",
    "focus": "must have + p.p.：過去の強い確信「〜したに違いない」",
    "question": "Mary must have lent some money to her brother because he was not rich enough to buy such a nice car.",
    "answer": "メアリーは彼女の兄［弟］にお金を貸したに違いない。彼はあんなにいい車を買えるほどお金持ちではなかったから。",
    "completed": "Mary must have lent some money to her brother because he was not rich enough to buy such a nice car.",
    "translation": "メアリーは彼女の兄［弟］にお金を貸したに違いない。彼はあんなにいい車を買えるほどお金持ちではなかったから。",
    "audioQ": "Mary must have lent some money to her brother because he was not rich enough to buy such a nice car.",
    "audioA": "Mary must have lent some money to her brother because he was not rich enough to buy such a nice car."
  },
  {
    "id": "evergreen.lesson10.1-(6)",
    "key": "1-(6)",
    "section": 1,
    "sectionName": "1 和訳 A",
    "format": "translate",
    "focus": "could have + p.p.：過去の可能性「〜したかもしれない」",
    "question": "My sister took part in the party, so she could have met John.",
    "answer": "姉［妹］はそのパーティーに参加したので，ジョンに会ったかもしれない。",
    "completed": "My sister took part in the party, so she could have met John.",
    "translation": "姉［妹］はそのパーティーに参加したので，ジョンに会ったかもしれない。",
    "audioQ": "My sister took part in the party, so she could have met John.",
    "audioA": "My sister took part in the party, so she could have met John."
  },
  {
    "id": "evergreen.lesson10.2-(1)",
    "key": "2-(1)",
    "section": 2,
    "sectionName": "2 語句整序 B・C",
    "format": "order",
    "focus": "might as well + V",
    "question": "[ your parents / you / well / might / tell / as ] the truth about the incident.",
    "answer": "You might as well tell your parents the truth about the incident.",
    "completed": "You might as well tell your parents the truth about the incident.",
    "translation": "あなたはご両親にその出来事の真実を告げたほうがよい。",
    "audioQ": "",
    "audioA": "You might as well tell your parents the truth about the incident."
  },
  {
    "id": "evergreen.lesson10.2-(2)",
    "key": "2-(2)",
    "section": 2,
    "sectionName": "2 語句整序 B・C",
    "format": "order",
    "focus": "may well + V",
    "question": "[ may / the baseball team / well / the championship / win ] this year.",
    "answer": "The baseball team may well win the championship this year.",
    "completed": "The baseball team may well win the championship this year.",
    "translation": "その野球チームはたぶん今年，優勝するだろう。",
    "audioQ": "",
    "audioA": "The baseball team may well win the championship this year."
  },
  {
    "id": "evergreen.lesson10.2-(3)",
    "key": "2-(3)",
    "section": 2,
    "sectionName": "2 語句整序 B・C",
    "format": "order",
    "focus": "It is important that S should + V",
    "question": "[ should / students / it / important / study / that / is ] hard.",
    "answer": "It is important that students should study hard.",
    "completed": "It is important that students should study hard.",
    "translation": "学生が熱心に勉強するのは重要なことだ。",
    "audioQ": "",
    "audioA": "It is important that students should study hard."
  },
  {
    "id": "evergreen.lesson10.2-(4)",
    "key": "2-(4)",
    "section": 2,
    "sectionName": "2 語句整序 B・C",
    "format": "order",
    "focus": "would like to + V",
    "question": "[ would / use / I / to / your eraser / like ].",
    "answer": "I would like to use your eraser.",
    "completed": "I would like to use your eraser.",
    "translation": "あなたの消しゴムを使いたいのですが。",
    "audioQ": "",
    "audioA": "I would like to use your eraser."
  },
  {
    "id": "evergreen.lesson10.2-(5)",
    "key": "2-(5)",
    "section": 2,
    "sectionName": "2 語句整序 B・C",
    "format": "order",
    "focus": "would rather A than B",
    "question": "[ rather / I / eat / than / out / would ] cook something.",
    "answer": "I would rather eat out than cook something.",
    "completed": "I would rather eat out than cook something.",
    "translation": "何かを料理するよりは，外食したい。",
    "audioQ": "",
    "audioA": "I would rather eat out than cook something."
  },
  {
    "id": "evergreen.lesson10.2-(6)",
    "key": "2-(6)",
    "section": 2,
    "sectionName": "2 語句整序 B・C",
    "format": "order",
    "focus": "suggest that S + 原形",
    "question": "I [ Bob / the next meeting / attend / that / suggest ] to discuss the matter.",
    "answer": "I suggest that Bob attend the next meeting to discuss the matter.",
    "completed": "I suggest that Bob attend the next meeting to discuss the matter.",
    "translation": "その件を議論するために，ボブが次の会議に出席することを私は提案する。",
    "audioQ": "",
    "audioA": "I suggest that Bob attend the next meeting to discuss the matter."
  },
  {
    "id": "evergreen.lesson10.3-(1)",
    "key": "3-(1)",
    "section": 3,
    "sectionName": "3 空所補充 総合",
    "format": "blank",
    "focus": "should have + p.p.：過去への非難・後悔",
    "question": "シュンは途中で博物館への道をだれかに尋ねるべきだった。／ Shun (　　　) (　　　) (　　　) someone the way to the museum on his way.",
    "answer": "should have asked",
    "completed": "Shun should have asked someone the way to the museum on his way.",
    "translation": "シュンは途中で博物館への道をだれかに尋ねるべきだった。",
    "audioQ": "Shun blank blank blank someone the way to the museum on his way.",
    "audioA": "Shun should have asked someone the way to the museum on his way."
  },
  {
    "id": "evergreen.lesson10.3-(2)",
    "key": "3-(2)",
    "section": 3,
    "sectionName": "3 空所補充 総合",
    "format": "blank",
    "focus": "cannot have + p.p.：過去の強い否定推量",
    "question": "メグが昨日，私に電話をしたはずがない。ずっといっしょにいたのだから。／ Meg (　　　) (　　　) (　　　) me yesterday because she was with me all day.",
    "answer": "cannot[can’t] have called",
    "completed": "Meg cannot have called me yesterday because she was with me all day.",
    "translation": "メグが昨日，私に電話をしたはずがない。ずっといっしょにいたのだから。",
    "audioQ": "Meg blank blank blank me yesterday because she was with me all day.",
    "audioA": "Meg cannot have called me yesterday because she was with me all day."
  },
  {
    "id": "evergreen.lesson10.3-(3)",
    "key": "3-(3)",
    "section": 3,
    "sectionName": "3 空所補充 総合",
    "format": "blank",
    "focus": "may as well A as B：BするのはAするようなものだ",
    "question": "ビルに何かを説明しようとするなんて，壁に話しかけるようなものだ。／ You may (　　　) (　　　) talk to the wall (　　　) try to explain something to Bill.",
    "answer": "as well, as",
    "completed": "You may as well talk to the wall as try to explain something to Bill.",
    "translation": "ビルに何かを説明しようとするなんて，壁に話しかけるようなものだ。",
    "audioQ": "You may blank blank talk to the wall blank try to explain something to Bill.",
    "audioA": "You may as well talk to the wall as try to explain something to Bill."
  },
  {
    "id": "evergreen.lesson10.3-(4)",
    "key": "3-(4)",
    "section": 3,
    "sectionName": "3 空所補充 総合",
    "format": "blank",
    "focus": "感情・評価の should：It is surprising that S should V",
    "question": "ディックとハンナが 2 週間後に結婚するなんてびっくりだ。／ It is surprising that Dick and Hannah (　　　) get married in two weeks.",
    "answer": "should",
    "completed": "It is surprising that Dick and Hannah should get married in two weeks.",
    "translation": "ディックとハンナが 2 週間後に結婚するなんてびっくりだ。",
    "audioQ": "It is surprising that Dick and Hannah blank get married in two weeks.",
    "audioA": "It is surprising that Dick and Hannah should get married in two weeks."
  },
  {
    "id": "evergreen.lesson10.3-(5)",
    "key": "3-(5)",
    "section": 3,
    "sectionName": "3 空所補充 総合",
    "format": "blank",
    "focus": "demand that S (should) + 原形",
    "question": "私たちはトムが次のバドミントン部のキャプテンになることを求めた。／ We demanded that Tom (　　　) the next captain of the badminton club.",
    "answer": "be[become]",
    "completed": "We demanded that Tom be the next captain of the badminton club.",
    "translation": "私たちはトムが次のバドミントン部のキャプテンになることを求めた。",
    "audioQ": "We demanded that Tom blank the next captain of the badminton club.",
    "audioA": "We demanded that Tom be the next captain of the badminton club."
  },
  {
    "id": "evergreen.lesson10.3-(6)",
    "key": "3-(6)",
    "section": 3,
    "sectionName": "3 空所補充 総合",
    "format": "blank",
    "focus": "should have + p.p.：過去の期待・推量",
    "question": "その学生たちは正午には東京を出発していたはずだ。／ The students (　　　) (　　　) (　　　) Tokyo at noon.",
    "answer": "should have left",
    "completed": "The students should have left Tokyo at noon.",
    "translation": "その学生たちは正午には東京を出発していたはずだ。",
    "audioQ": "The students blank blank blank Tokyo at noon.",
    "audioA": "The students should have left Tokyo at noon."
  },
  {
    "id": "evergreen.lesson10.TRY-(1)",
    "key": "TRY-(1)",
    "section": 4,
    "sectionName": "TRY 英作文",
    "format": "write",
    "focus": "must have + p.p.",
    "question": "シンジは新しい自転車を買ったに違いない。",
    "answer": "Shinji must have bought a new bike.",
    "completed": "Shinji must have bought a new bike.",
    "translation": "シンジは新しい自転車を買ったに違いない。",
    "audioQ": "",
    "audioA": "Shinji must have bought a new bike."
  },
  {
    "id": "evergreen.lesson10.TRY-(2)",
    "key": "TRY-(2)",
    "section": 4,
    "sectionName": "TRY 英作文",
    "format": "write",
    "focus": "may/might/could have + p.p.",
    "question": "ルーシーはこのレストランで夕食を食べたかもしれない。",
    "answer": "Lucy may[might / could] have eaten[had] dinner at this restaurant.",
    "completed": "Lucy may have eaten dinner at this restaurant.",
    "translation": "ルーシーはこのレストランで夕食を食べたかもしれない。",
    "audioQ": "",
    "audioA": "Lucy may have eaten dinner at this restaurant."
  },
  {
    "id": "evergreen.lesson10.TRY-(3)",
    "key": "TRY-(3)",
    "section": 4,
    "sectionName": "TRY 英作文",
    "format": "write",
    "focus": "would like to + V",
    "question": "この本を借りたいと思うのですが。（like を用いて）",
    "answer": "I’d[I would] like to borrow this book.",
    "completed": "I would like to borrow this book.",
    "translation": "この本を借りたいと思うのですが。（like を用いて）",
    "audioQ": "",
    "audioA": "I would like to borrow this book."
  },
  {
    "id": "evergreen.lesson10.TRY-(4)",
    "key": "TRY-(4)",
    "section": 4,
    "sectionName": "TRY 英作文",
    "format": "write",
    "focus": "It is important that S (should) V",
    "question": "宿題はあなたが 1 人でやることが重要だ。",
    "answer": "It is important that you (should) do your homework by yourself.",
    "completed": "It is important that you should do your homework by yourself.",
    "translation": "宿題はあなたが 1 人でやることが重要だ。",
    "audioQ": "",
    "audioA": "It is important that you should do your homework by yourself."
  }
];
